name: /ext3/conda/zillow_MMKG
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - asttokens=2.0.5=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - brotlipy=0.7.0=py38h0a891b7_1004
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.12.7=ha878542_0
  - catalogue=2.0.6=py38h578d9bd_2
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py38h4a40e3a_0
  - chardet=5.0.0=py38h578d9bd_0
  - charset-normalizer=2.1.0=pyhd8ed1ab_0
  - cmake=3.23.3=h5432695_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - conda-package-handling=1.8.1=py38h0a891b7_1
  - cryptography=37.0.4=py38h2b5fc30_0
  - cymem=2.0.6=py38hfa26641_3
  - cython-blis=0.7.8=py38h71d37f0_0
  - dataclasses=0.8=pyhc8e2a94_3
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.0.4=pyhd8ed1ab_0
  - executing=0.9.1=pyhd8ed1ab_0
  - expat=2.4.8=h27087fc_0
  - filelock=3.7.1=pyhd8ed1ab_0
  - glob2=0.7=py_0
  - hydra-core=1.3.0=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib_resources=5.10.1=pyhd8ed1ab_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - ipython=8.4.0=py38h578d9bd_0
  - jedi=0.18.1=py38h578d9bd_1
  - jinja2=3.1.2=pyhd8ed1ab_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - langcodes=3.3.0=pyhd8ed1ab_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libarchive=3.5.2=hb890918_3
  - libblas=3.9.0=15_linux64_openblas
  - libcblas=3.9.0=15_linux64_openblas
  - libcurl=7.83.1=h7bff187_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=15_linux64_openblas
  - liblief=0.11.5=h9c3ff4c_1
  - libllvm10=10.0.1=he513fc3_3
  - libnghttp2=1.47.0=h727a467_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.20=pthreads_h78a6416_1
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.44.2=h166bdaf_0
  - libxml2=2.9.14=h22db469_3
  - libzlib=1.2.12=h166bdaf_2
  - llvm-openmp=14.0.4=he0ac6c6_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - lzo=2.10=h516909a_1000
  - markupsafe=2.1.1=py38h0a891b7_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mkl=2020.4=h726a3e6_304
  - mkl-include=2020.4=h726a3e6_304
  - mock=4.0.3=py38h578d9bd_3
  - murmurhash=1.0.7=py38hfa26641_0
  - ncurses=6.3=h27087fc_1
  - ninja=1.11.0=h924138e_0
  - omegaconf=2.2.3=py38h578d9bd_0
  - openblas=0.3.20=pthreads_h320a7e8_1
  - openssl=1.1.1s=h0b41bf4_1
  - packaging=21.3=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patch=2.7.6=h7f98852_1002
  - patchelf=0.15.0=h58526e2_0
  - pathy=0.6.2=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=21.2.4=pyhd8ed1ab_0
  - pkginfo=1.8.3=pyhd8ed1ab_0
  - pluggy=1.0.0=pyhd8ed1ab_5
  - preshed=3.0.6=py38hfa26641_2
  - prompt-toolkit=3.0.30=pyha770c72_0
  - psutil=5.9.1=py38h0a891b7_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-lief=0.11.5=py38h709712a_1
  - pycosat=0.6.3=py38h0a891b7_1010
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.9.1=py38h0a891b7_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=py38h578d9bd_5
  - python=3.8.13=h582c2e5_0_cpython
  - python-libarchive-c=4.0=py38h578d9bd_1
  - python_abi=3.8=2_cp38
  - pytz=2022.1=pyhd8ed1ab_0
  - pyyaml=6.0=py38h0a891b7_4
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=pyhd8ed1ab_0
  - rhash=1.4.3=h166bdaf_0
  - ripgrep=13.0.0=h2f28480_2
  - ruamel_yaml=0.15.80=py38h0a891b7_1007
  - setuptools=59.5.0=py38h578d9bd_0
  - shellingham=1.4.0=pyh44b312d_0
  - six=1.16.0=pyh6c4a22f_0
  - smart_open=5.2.1=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - spacy=3.4.1=py38h514daf8_0
  - spacy-legacy=3.0.9=pyhd8ed1ab_0
  - spacy-loggers=1.0.2=pyhd8ed1ab_0
  - sqlite=3.39.2=h4ff8645_0
  - srsly=2.4.4=py38hfa26641_0
  - stack_data=0.3.0=pyhd8ed1ab_0
  - thinc=8.1.0=py38h514daf8_0
  - tk=8.6.12=h27826a3_0
  - tmux=3.3=h385fc29_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.3.0=pyhd8ed1ab_0
  - typer=0.4.2=pyhd8ed1ab_0
  - typing-extensions=4.3.0=hd8ed1ab_0
  - typing_extensions=4.3.0=pyha770c72_0
  - tzdata=2022a=h191b570_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wasabi=0.10.0=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.12=h166bdaf_2
  - zstd=1.5.2=h8a70e8d_2
  - pip:
    - absl-py==1.2.0
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - alabaster==0.7.12
    - apex==0.1
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - async-timeout==4.0.2
    - audioread==2.1.9
    - autopep8==2.0.1
    - babel==2.10.3
    - better-profanity==0.7.0
    - bleach==5.0.1
    - cachetools==5.2.0
    - click==8.0.4
    - cloudpickle==2.1.0
    - codecov==2.1.12
    - conllu==4.5.2
    - coverage==6.4.2
    - cuda-python==11.6.0
    - cudf==22.6.0a0+319.g97422602b8
    - cugraph==22.6.0a0+114.gc6bc8867
    - cuml==22.6.0a0+71.g59a124168
    - cupy-cuda115==10.5.0
    - cycler==0.11.0
    - cython==0.29.32
    - dask==2022.5.2
    - dask-cuda==22.6.0
    - dask-cudf==22.6.0a0+319.g97422602b8
    - datasets==2.7.1
    - debugpy==1.6.2
    - defusedxml==0.7.1
    - dgl-cu116==0.9.1.post1
    - dglgo==0.0.2
    - dill==0.3.6
    - distributed==2022.5.2
    - docutils==0.17.1
    - entrypoints==0.3
    - expecttest==0.1.3
    - fastjsonschema==2.16.1
    - fastrlock==0.8
    - flake8==3.7.9
    - flask==2.2.1
    - fonttools==4.34.4
    - frozenlist==1.3.3
    - fsspec==2022.7.1
    - ftfy==6.1.1
    - future==0.18.2
    - google-auth==2.9.1
    - google-auth-oauthlib==0.4.6
    - graphsurgeon==0.4.6
    - grpcio==1.47.0
    - heapdict==1.0.1
    - huggingface-hub==0.11.1
    - hypothesis==4.50.8
    - imagesize==1.4.1
    - importlib-metadata==4.12.0
    - importlib-resources==5.9.0
    - iopath==0.1.10
    - ipykernel==6.15.1
    - ipython-genutils==0.2.0
    - isort==5.11.2
    - itsdangerous==2.1.2
    - joblib==1.1.0
    - json5==0.9.9
    - jsonschema==4.9.1
    - jupyter-client==7.3.4
    - jupyter-core==4.11.1
    - jupyter-tensorboard==0.2.0
    - jupyterlab==2.3.2
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==1.2.0
    - jupytext==1.14.1
    - kiwisolver==1.4.4
    - librosa==0.9.2
    - lightning-utilities==0.4.2
    - littleutils==0.2.2
    - llvmlite==0.39.0
    - lmdb==1.3.0
    - locket==1.0.0
    - markdown==3.4.1
    - markdown-it-py==2.1.0
    - matplotlib==3.5.2
    - mccabe==0.6.1
    - mdit-py-plugins==0.3.0
    - mdurl==0.1.1
    - mistune==0.8.4
    - msgpack==1.0.4
    - multidict==6.0.3
    - multiprocess==0.70.14
    - nbclient==0.6.6
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - networkx==2.6.3
    - nltk==3.7
    - notebook==6.4.10
    - numba==0.56.0
    - numpy==1.23.5
    - numpydoc==1.5.0
    - nvidia-dali-cuda110==1.16.0
    - nvidia-pyindex==1.0.9
    - nvtx==0.2.5
    - oauthlib==3.2.0
    - ogb==1.3.5
    - onnx==1.12.0
    - outdated==0.2.2
    - pandas==1.4.3
    - pandocfilters==1.5.0
    - partd==1.2.0
    - pillow==9.0.1
    - pkgutil-resolve-name==1.3.10
    - polygraphy==0.33.0
    - pooch==1.6.0
    - portalocker==2.5.1
    - prettytable==3.3.0
    - prometheus-client==0.14.1
    - protobuf==3.20.1
    - py==1.11.0
    - pyarrow==7.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.10.0
    - pycocotools==2.0+nv0.6.0
    - pycodestyle==2.10.0
    - pydot==1.4.2
    - pyflakes==2.1.1
    - pylibcugraph==22.6.0a0+114.gc6bc8867
    - pynvml==11.4.1
    - pyrootutils==1.0.4
    - pyrsistent==0.18.1
    - pytest==6.2.5
    - pytest-cov==3.0.0
    - pytest-pythonpath==0.7.4
    - python-dateutil==2.8.2
    - python-dotenv==0.21.0
    - python-hostlist==1.21
    - python-nvd3==0.15.0
    - python-slugify==6.1.2
    - pytorch-lightning==1.8.5.post0
    - pytorch-quantization==2.1.2
    - pyzmq==23.2.0
    - raft==22.6.0a0+85.g3e5a625
    - rdkit-pypi==2022.9.3
    - regex==2022.7.25
    - requests-oauthlib==1.3.1
    - resampy==0.3.1
    - responses==0.18.0
    - revtok==0.0.3
    - rmm==22.6.0a0+76.g185c18e6
    - rsa==4.9
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.7
    - sacremoses==0.0.53
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - send2trash==1.8.0
    - simcse==0.4
    - sniffio==1.3.0
    - snowballstemmer==2.2.0
    - sortedcontainers==2.4.0
    - soundfile==0.10.3.post1
    - sphinx==5.1.1
    - sphinx-glpi-theme==0.3
    - sphinx-rtd-theme==1.0.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - tabulate==0.8.10
    - tblib==1.7.0
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - tensorrt==8.4.2.4
    - terminado==0.15.0
    - text-unidecode==1.3
    - textblob==0.17.1
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - tokenizers==0.12.1
    - toml==0.10.2
    - toolz==0.12.0
    - torch==1.13.0a0+d321be6
    - torch-tb-profiler==0.4.0
    - torch-tensorrt==1.2.0a0
    - torchmetrics==0.11.0
    - torchtext==0.11.0a0
    - torchvision==0.14.0a0
    - tornado==6.2
    - transformers==4.24.0
    - treelite==2.4.0
    - treelite-runtime==2.4.0
    - tweepy==4.12.1
    - uc-micro-py==1.0.1
    - ucx-py==0.26.0a0+19.g1b942b8
    - uff==0.6.9
    - webencodings==0.5.1
    - werkzeug==2.2.1
    - xgboost==1.6.1
    - xxhash==3.1.0
    - yarl==1.8.2
    - zict==2.2.0
    - zipp==3.8.1
prefix: /ext3/conda/zillow_MMKG
